version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: auditlog
    container_name: auditlog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
